name: Update GeoJSON

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixpkgs-23.11-darwin
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.nixos.org/

      - name: Install dependencies
        run: |
          nix-shell --pure --run true

      - name: Generate GeoJSON
        run: |
          nix-shell --pure --run "python main.py"

      - name: Remove files larger than 100MB
        run: |
          find geojson -type f -size +100M -delete

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Update GeoJSON"

      - name: Clean git history
        run: |
          nix-shell --pure -p bfg-repo-cleaner --run "bfg --delete-folders geojson"
          git reflog expire --expire=now --all && git gc --prune=now --aggressive

      - name: Push changes
        run: |
          git push --force
